# Generated by Django 4.2.4 on 2023-08-18 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import file.models
import file.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=200, upload_to=file.models.get_upload_path, validators=[file.validators.validate_file], verbose_name='Файл')),
                ('downloads_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('status', models.CharField(choices=[('new', 'новый'), ('updated', 'обновлен')], default='new', verbose_name='Статус')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
